services:
  app:
    container_name: app
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "php:8.3"
    volumes:
      - ./backend:/var/www
    working_dir: "/var/www/project"
    tty: true
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www
    depends_on:
      - app
  db: # mysql -h localhost -u user -ppass
    container_name: db
    image: mysql:8.4
    ports:
      - 3306:3306
    volumes:
      - ./mysql/script:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
volumes:
  db-store:
    name: db-store
