services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_u
      MYSQL_PASSWORD: wordpress
    volumes:
      - data-db:/var/lib/mysql

  wordpress:
    image: wordpress:6.0
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_u
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html

volumes:
  data-db: